### ISSUE TITLE
Official instance migration to fly.io

### ISSUE THREAD

**Issue by xvello** [letsblockit/letsblockit#356]
In order to simplify operations and reduce latency for international users, I am currently moving the letsblock.it official instance's server from its Hetzner VPS into a fly.io service:

- It currently runs two instances, in Amsterdam and Los Angeles, so I expect users in America and Asia to experience faster response times
- The database stays hosted in Germany, on a Hetzner VPS
- The authentication stays hosted on Ory Network's European region
- The service is now automatically deployed on every merge to `main`, instead of requiring manual operations

Please use this issue to report any kinks that you might be experiencing.

## Measured latency

This graphs shows the time to load https://letsblock.it/filters/ for an anonymous user (we don't hit the DB) from several locations. Bottom to top on the latest values is: Paris, California (western US), Virginia (eastern US), Tokyo, Seoul:

![Response Time to homepage](https://user-images.githubusercontent.com/6241083/218443175-6ecab4e6-028a-41de-a4ca-ab528c25e47f.png)

A big chunk of the remaining latency is the uncached DNS resolution to Gandi's nameservers, but we can expect this resolution to be cached by most residential ISPs.

## For statistic nerds, the official instances currently serves:
  - 415 different active lists (downloaded at least once per week), totaling 1196 active filter instances
  - Around 300k requests per month, totaling 1GB of outgoing bandwidth per month

## TODO:
  - [x] bring back logs and metrics, maybe through vector?
  - [x] add metric on pg query latency (we're not running on the same server anymore)
  - [x] update [the privacy page](https://letsblock.it/help/privacy), and add fly.io to the sponsor section
  - [x] redirect www to root domain (used to do it with nginx)

**Comment by xvello** [comment]
This change was reverted, see more info in https://github.com/letsblockit/letsblockit/pull/365

While this sped up the initial page load for anonymous users, it significantly degraded performance for logged-in users. The server is back in Nuremberg, alongside the database.
